### ISSUE TITLE
HTTP Error

### ISSUE THREAD

**Issue by whatever-T-C** [Justmalhar/open-audio#2]
![螢幕擷取畫面 2023-12-15 011316](https://github.com/Justmalhar/open-audio/assets/143330343/6aedfadb-2dee-4586-b6e1-777d3b2e5349)

edit: forget it, my bad, I use an invalid key

**Comment by whatever-T-C** [comment]
also I found this: https://github.com/0xAndreiD/OpenAI-TTS
is this also your account?

**Comment by Justmalhar** [comment]
> also I found this: https://github.com/0xAndreiD/OpenAI-TTS is this also your account?

It seems to be a fork of the repo
