### ISSUE TITLE
speed control not work in live demo

### ISSUE THREAD

**Issue by bfcs** [Justmalhar/open-audio#3]
Hi, 
I tried sliding the speed control button, but it had no effect.
<img width="573" alt="image" src="https://github.com/Justmalhar/open-audio/assets/52602045/da6e4fb6-d4ae-40ca-8776-22051dc5d991">

**Comment by Justmalhar** [comment]
The slider in screenshot is already at max value supported by the API. Did you try lowering it? Would be cool to print its value to see what’s being called. 

Happy to help with a patch if it’s still an issue

**Comment by bfcs** [comment]
Hi, @Justmalhar 
I've tried so change the speed, it keeps the same
<img width="1215" alt="image" src="https://github.com/Justmalhar/open-audio/assets/52602045/b3ef3c2b-bd86-4c01-a89f-9c5455470b3d">

**Comment by Justmalhar** [comment]
I tested it, the slider works. 1x-4x
