### ISSUE TITLE
How to add environment variables

### ISSUE THREAD

**Issue by billowssun** [Justmalhar/open-audio#6]

**Comment by Justmalhar** [comment]
You can go to Vercel and look for Environment Variables in Project Settings. For local development, create a .env or .env.local file with the environment variable

**Comment by Justmalhar** [comment]
Optionally you can also modify this and use the setter to read value from environment variable

https://github.com/Justmalhar/open-audio/blob/68c10417f15303bea7f5031dc84ce0723145c4df/src/pages/index.js#L34
